export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const ADD_EXPENSE = 'ADD_EXPENSE'
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE'
export const EDIT_EXPENSE = 'EDIT_EXPENSE'
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS'
export const FETCH_EXPENSES_ERROR = 'FETCH_EXPENSES_ERROR'

export const SET_TEXT = 'SET_TEXT'
export const SORT_BY_AMOUNT = 'SORT_BY_AMOUNT'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SET_START_DATE = 'SET_START_DATE'
export const SET_END_DATE = 'SET_END_DATE'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'